### ISSUE TITLE
HV launched into space at 1 million m/s

### ISSUE THREAD

**Issue by alaskascooter** [RavienGaming/Reforged-Eden-2#77]
### Reforged Eden 2 Build Number

7

### Game mode

Survival, Single Player

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Traveling in HV, hit tree/rock. HV then launched into the sky and out of sector. Once the sector loaded HV reported a speed almost 1 million m/s and unable to slow. Eventually started receiving error of sector border.

I do not know how it happened, how to reproduce, or if it is a RE2 or vanilla issue.

### Error code from console or log (Optional)

no error presented

### Game Seed

266332

**Comment by RavienGaming** [comment]
This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by VermillionX** [comment]
Potentially fixed in next update... to some degree. Maybe?

**Comment by SketchyGFG** [comment]
We are still getting reports of this on No Man's Land but nobody has reproduced on vanilla yet to my knowledge

**Comment by RavienGaming** [comment]
> We are still getting reports of this on No Man's Land but nobody has reproduced on vanilla yet to my knowledge

Would need to be reproduced and reported in vanilla using the same game mode (sp/coop/dedi, surv/freedom/creative). If the attempted fix we did did not solve the issue, then it's likely a game bug. I will attach the steps to report it below:

This is likely a game bug and will need to be reproduced and reported using a vanilla save game.
When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by Multox** [comment]
I've played hundreds of hours in vanilla and never seen this.  On the other hand, I've been launched into space twice in the last two days in RE2.

Both times I was travelling at max HV speed and travelling across country for a lengthy distance.  Each time, I hit something that launched me upwards.  Simultaneously, there was a very large framerate stutter - possibly terrain or texture loading.  

Depending on game limitations, the fix might be as simple as forcing the current velocity into a constrained range such as +-500.

**Comment by RavienGaming** [comment]
> I've played hundreds of hours in vanilla and never seen this. On the other hand, I've been launched into space twice in the last two days in RE2.
> 
> Both times I was travelling at max HV speed and travelling across country for a lengthy distance. Each time, I hit something that launched me upwards. Simultaneously, there was a very large framerate stutter - possibly terrain or texture loading.
> 
> Depending on game limitations, the fix might be as simple as forcing the current velocity into a constrained range such as +-500.

Were you playing vanilla in single player and RE2 in multiplayer?
Regardless, there's nothing we can do to fix this within the limits scenarios operate under. This would be for Eleon to fix.

**Comment by Multox** [comment]
> Were you playing vanilla in single player and RE2 in multiplayer?
> Regardless, there's nothing we can do to fix this within the limits scenarios operate under. This would be for Eleon to fix.

Vanilla time spent both in single player and multiplayer.  Most recently I played through the Dark Faction campaign in vanilla single player.  RE2 time so far has also been single player.

Understood about it being unfixable by a scenario.  Thank you for RE2, it's amazing!  Totally worth a few minor issues like this.

**Comment by UlfB44** [comment]
Played SP RE2 and was launched into space after hitting a tree.

never had this occur in vanilla.

**Comment by RavienGaming** [comment]
> Played SP RE2 and was launched into space after hitting a tree.
> 
> never had this occur in vanilla.

Yup until someone reproduces it in vanilla and reports it to the developers it won't be fixed.

**Comment by ChristopherPisz** [comment]
This occurred to me and is 100% reproducible via my save game.
I can only make it happen in Reforged Eden 2.

Steps:
1) use the attached save
2) enter the hovercraft miner
3) Head towards the copper deposit to the SW
4) Go full speed and run over small rocks that do not stop you, but make you pitch
5) Continue doin so until the bug happens
6) Observe game hangs for a second or two and teleports you to space
7) Observe Internal Error Reforged Eden 2 dialog.

Extra steps:
1) Spawn the same miner into vanilla
2) Go top speed and run over rocks in the same way
3) Observe the problem does not occur

Special observances:
1) It seems to me that vanilla creative single player does not allow me to pitch my nose up and while driving it is almost always pitched down
2) Note that in both RE and vanilla, the clearance from ground is 2m with this vehicle.

[Poopy Doopy Doo-260913-1358.zip](https://github.com/user-attachments/files/32166643/Poopy.Doopy.Doo-260913-1358.zip)

<img width="1919" height="1075" alt="Image" src="https://github.com/user-attachments/assets/4aa2d50e-b9c4-4f11-aef4-003c9cf786e0" />

**Comment by RavienGaming** [comment]
> This occurred to me and is 100% reproducible via my save game. I can only make it happen in Reforged Eden 2.
> 
> Steps:
> 
> 1. use the attached save
> 2. enter the hovercraft miner
> 3. Head towards the copper deposit to the SW
> 4. Go full speed and run over small rocks that do not stop you, but make you pitch
> 5. Continue doin so until the bug happens
> 6. Observe game hangs for a second or two and teleports you to space
> 7. Observe Internal Error Reforged Eden 2 dialog.
> 
> Extra steps:
> 
> 1. Spawn the same miner into vanilla
> 2. Go top speed and run over rocks in the same way
> 3. Observe the problem does not occur
> 
> Special observances:
> 
> 1. It seems to me that vanilla creative single player does not allow me to pitch my nose up and while driving it is almost always pitched down
> 2. Note that in both RE and vanilla, the clearance from ground is 2m with this vehicle.
> 
> [Poopy Doopy Doo-260913-1358.zip](https://github.com/user-attachments/files/32166643/Poopy.Doopy.Doo-260913-1358.zip)
> 
> <img alt="Image" width="1919" height="1075" src="https://private-user-images.githubusercontent.com/23269952/650967755-4aa2d50e-b9c4-4f11-aef4-003c9cf786e0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODkzMjc2OTUsIm5iZiI6MTc4OTMyNzM5NSwicGF0aCI6Ii8yMzI2OTk1Mi82NTA5Njc3NTUtNGFhMmQ1MGUtYjljNC00ZjExLWFlZjQtMDAzYzljZjc4NmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwOTEzVDE5MjMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOWI4ODgwN2NlMDA2YzAzYWM2ZjIwYWRkMmM5NzQ5NzYwZjgxMTMwNjc4NjAxMDY1NmYyOGM0N2FlODI3MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.iR9zdL9zfTY17fNyWg7Cp1EI0S1q3c9CyZHqAkdF-u4">


Yeah like I said above unfortunately until someone is able to reproduce it in a vanilla save and then report it to Eleon using their official bug report system, this will not be fixed. There is nothing in the config settings available to scenarios that would be able to change the flight physics. That is entirely and wholly in the game developer's ability to fix. No player created scenario or patch or mod or config change can change the game's physics unfortunately.

**Comment by ChristopherPisz** [comment]
Note the difference in pitch permitted between reforged eden 2 and vanilla.

I am not an experienced empyrion player, but it seems to me vanilla does not allow me to pitch up my HV and Reforged Eden does. I'd think this makes the physic go bonkers when it tried to calculate what happens when we hit a small rock while driving. Vanilla forces me to stop, and the vehicle pitches towards the ground. RE launches me into space.

So, it is my theory that reforged eden is the only place this bug can occur, because the vanilla devs limit the pitch of the HV covering it up. When Reforged Eden removed the pitch restriction, they allow the annoying bug.

Screenshots attached for compare in pitch

Reforged Eden scrolling trackball as screenshot pressed:
<img width="1757" height="1042" alt="Image" src="https://github.com/user-attachments/assets/e43946ee-eb97-4d5c-8c44-6950f5493df9" />

Vanilla scrolling trackball as screenshot pressed:
<img width="1749" height="1065" alt="Image" src="https://github.com/user-attachments/assets/ef1a7322-388a-478d-8136-2048b99c3d30" />

P.S:
I am currently an unemployed SE with 20 years of C++, if anyone wants to hire me for my awesome debugging skills :p

**Comment by ChristopherPisz** [comment]
The HV in testing has docking pads lower to the ground than the hover engines. 

I removed those and so far am not able to cause the craft to bug out. This might be an additional factor and/or workaround. I'll keep playing where hover engines are the lowest thing to the ground on the vehicles and see if it occurs again. I also suspect stronger hover engines might put the vehicle off the ground with enough clearance where it does not occur, but will have to test too.

**Comment by RavienGaming** [comment]
> So, it is my theory that reforged eden is the only place this bug can occur, because the vanilla devs limit the pitch of the HV covering it up. When Reforged Eden removed the pitch restriction, they allow the annoying bug.

As I said, scenarios have no access to the game's physics or flight models. There is absolutely, positively, 100% nothing that can be changed within a scenario in regards to HV (or any) collision or flight physics or model or anything of the sort.
This is, as I said earlier, completely in the realm of the devs, and is not fixable or modifiable within a scenario.

Scenarios have zero access to any game code like that and **cannot** make the change you referenced.

**Comment by ChristopherPisz** [comment]
I don't know why you keep repeating that line every time the issue is talked about. No physics change is being asked for.

The issue, as far as testing shows vs vanilla is due to allowing HVs to pitch up. You absolutely can change that, because the mod allows it while vanilla doesn't. However, I wouldn't suggest you do that, as it is quite nice compared to vanilla, as long as everyone understands the bug and its nature, as a result.

What I do suggest, is that we document what was found and suggest the workaround as described until someone reports that didn't work for them.

**Comment by RavienGaming** [comment]
> The issue, as far as testing shows vs vanilla is due to allowing HVs to pitch up. You absolutely can change that, because the mod allows it while vanilla doesn't.

No, this isn't something that is available to scenarios. As I said, scenarios have no access to the game code, nor any configuration options for the flight or physics models. This is nothing that was changed in RE2 as scenarios do not have that as an option.
Any pitch change is due to the differences in a HV's blueprint and relative mass, thrust, and torque differences between vanilla and RE2. If you add more torque and/or thrust and/or reduce mass of a HV blueprint, you can pitch a HV up in vanilla too.

**Comment by ChristopherPisz** [comment]
> > The issue, as far as testing shows vs vanilla is due to allowing HVs to pitch up. You absolutely can change that, because the mod allows it while vanilla doesn't.
> 
> No, this isn't something that is available to scenarios.

Well, no HV in my library allows me to pitch up in vanilla and I've tried a good three dozen of them today.
All the exact same blueprints pitch up in reforged eden. Every single one. No changes to any of them. Spawn and go.

So, I dunno how that occurs without it being modded somewhere directly or indirectly. Perhaps indirectly due to torque on RCS in the mod.

Either way, I am not asking for any changes, so no sense in arguing about it. I simply wanted to report my findings for the next guy who has the same problem. Thanks for the mod and keep up the good work.

**Comment by VermillionX** [comment]
Hover Engines in RE2 provide torque, the same as an RCS. HVs that you've used in vanilla cannot pitch up because no one puts an RCS on them, largely because they're so underpowered and massively over CPU, weight and power that RCS in vanilla aren't practical.
If someone wants their HV to pitch up or down now, they use up/down thrusters. They don't provide any thrust in those directions at all, but they still provide torque in that direction; and pitch is vital for HVs to be able to mine downward or shoot upwards.

**Comment by ChristopherPisz** [comment]
This morning I still experience the bug even though I got rid of blocks lower than engines and upgraded them to large, so that isn't a valid workaround, although I think it occurred less often... but that's just loose opinion.

I also tried cockpit view and thought that made it less often as well for awhile, but then it started happening again at least twice an hour.
Back to having no clue and no workaround, which sucks. It's near impossible to use an HV as often as this occurs and how much time it takes to go teleport, respawn the ship when the generators blow up, estimate the content, spawn those in, and then re-travel where you were going only to have it happen again.

I've been trying real hard to make it happen in vanilla and just can't make it happen there. If anyone finds any work around, such that we can use an HV on Akua without this happening as often, let us know.

**Comment by RavienGaming** [comment]
You'd likely need to make a blueprint specifically for vanilla that has more torque and therefor flies like a HV does in RE2, then spend a good 10+ hours driving it around in similar environments as you do in RE2. Probably more like 100+ hours to reliably reproduce it as it is a rare bug (though you are unlucky it sounds like).
It is unfortunate and a lot of work so I do not expect anyone to do this, but for game bugs unfortunately this is the amount of work that is required in order to report some game bugs. Trust me, I know, I myself have spent easily a dozen+ hours trying to figure out and report a game bug myself too before.

It's not fun, it's unpaid labor, and so I never expect anyone to do it but the reality is that unless a player does this work to reproduce in a vanilla save game, the devs will not even be aware of the bug to know it needs fixing.

There's nothing in the scenario that could cause this specifically. As Vermillion mentioned, vanilla HVs are typically built differently, not because of any different flight physics or modded collisions or such, but because of simple torque, thrust, and mass values for everything being different. This means if you want to reliably reproduce the same issue in a vanilla game, you need to typically setup a 1 to 1 equivalent in vanilla for exactly what happened in RE2.

This means testing in the same mode (sp, coop, dedi, creative, survival, etc), on a planet with a similar terrain and biome decorations, using a HV that has the same size, mass, thrust, and torque values, the same center of mass and pivot point, the same top speed, etc. All those values need to be made as close as possible. And then it will potentially take you tens of hours of testing over and over and over again.

Like I said though, until someone does this testing and reproduces the issue in a vanilla save game, then uploads the save, blueprint, and logs in an official bug report to the developers, there will be no fix coming.

I really wish I had something more useful to say, but this really is out of Vermillion and my hands. There's just literally no settings in the scenario to change this, and I would not want to nerf HV agility as a bandaid fix for a game physics calculation error that may not even work as a bandaid fix.
